#!/bin/bash
# CSPR-CDP Frontend Binding Script
#
# Updates frontend configuration with deployed contract addresses.
# Usage: ./bind-frontend.sh [network] [deployment-file]

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
FRONTEND_DIR="$ROOT_DIR/../frontend"
DEPLOY_DIR="$ROOT_DIR/../deployments/casper"
CONFIG_DIR="$ROOT_DIR/../config"
PUBLIC_CONFIG_DIR="$FRONTEND_DIR/public/config"

NETWORK="${1:-testnet}"
DEPLOY_FILE="${2:-}"

echo "=== CSPR-CDP Frontend Binding ==="
echo "Network: $NETWORK"
echo ""

# Find latest deployment file if not specified
if [ -z "$DEPLOY_FILE" ]; then
    DEPLOY_FILE=$(ls -t "$DEPLOY_DIR/${NETWORK}-"*.json 2>/dev/null | head -n1)
    if [ -z "$DEPLOY_FILE" ]; then
        echo "ERROR: No deployment file found for network: $NETWORK"
        echo "Run deploy.sh first or specify deployment file."
        exit 1
    fi
fi

echo "Deployment file: $DEPLOY_FILE"
echo ""

# Parse deployment file
if ! command -v jq &> /dev/null; then
    echo "ERROR: jq is required. Install with: brew install jq"
    exit 1
fi

NODE_ADDRESS=$(jq -r '.nodeAddress' "$DEPLOY_FILE")
CHAIN_NAME=$(jq -r '.chainName' "$DEPLOY_FILE")

# Frontend expects the JSON-RPC endpoint (typically ends with /rpc).
FRONTEND_NODE_ADDRESS="$NODE_ADDRESS"
if [[ "$FRONTEND_NODE_ADDRESS" != */rpc ]]; then
    FRONTEND_NODE_ADDRESS="${FRONTEND_NODE_ADDRESS%/}/rpc"
fi

# Extract contract hashes
REGISTRY_HASH=$(jq -r '.contracts.registry.hash // "null"' "$DEPLOY_FILE")
ROUTER_HASH=$(jq -r '.contracts.router.hash // "null"' "$DEPLOY_FILE")
ROUTER_PKG_HASH=$(jq -r '.contracts.router.package_hash // "null"' "$DEPLOY_FILE")
STABLECOIN_HASH=$(jq -r '.contracts.stablecoin.hash // "null"' "$DEPLOY_FILE")
ORACLE_HASH=$(jq -r '.contracts.oracleAdapter.hash // "null"' "$DEPLOY_FILE")
STABILITY_POOL_HASH=$(jq -r '.contracts.stabilityPool.hash // "null"' "$DEPLOY_FILE")
STABILITY_POOL_PKG_HASH=$(jq -r '.contracts.stabilityPool.package_hash // "null"' "$DEPLOY_FILE")
LIQUIDATION_ENGINE_HASH=$(jq -r '.contracts.liquidationEngine.hash // "null"' "$DEPLOY_FILE")
REDEMPTION_ENGINE_HASH=$(jq -r '.contracts.redemptionEngine.hash // "null"' "$DEPLOY_FILE")
TREASURY_HASH=$(jq -r '.contracts.treasury.hash // "null"' "$DEPLOY_FILE")
BRANCH_CSPR_HASH=$(jq -r '.contracts.branchCspr.hash // "null"' "$DEPLOY_FILE")
BRANCH_SCSPR_HASH=$(jq -r '.contracts.branchSCSPR.hash // "null"' "$DEPLOY_FILE")
SCSPR_YBTOKEN_HASH=$(jq -r '.contracts.scsprYbToken.hash // "null"' "$DEPLOY_FILE")
SCSPR_YBTOKEN_PKG_HASH=$(jq -r '.contracts.scsprYbToken.package_hash // "null"' "$DEPLOY_FILE")
WITHDRAW_QUEUE_HASH=$(jq -r '.contracts.withdrawQueue.hash // "null"' "$DEPLOY_FILE")

# Create frontend config
mkdir -p "$CONFIG_DIR"
mkdir -p "$PUBLIC_CONFIG_DIR"

cat > "$CONFIG_DIR/casper-${NETWORK}.json" << EOF
{
  "network": "$NETWORK",
  "chainName": "$CHAIN_NAME",
  "nodeAddress": "$FRONTEND_NODE_ADDRESS",
  "contracts": {
    "registry": "$REGISTRY_HASH",
    "router": "$ROUTER_HASH",
    "routerPackage": "$ROUTER_PKG_HASH",
    "stablecoin": "$STABLECOIN_HASH",
    "oracleAdapter": "$ORACLE_HASH",
    "stabilityPool": "$STABILITY_POOL_HASH",
    "stabilityPoolPackage": "$STABILITY_POOL_PKG_HASH",
    "liquidationEngine": "$LIQUIDATION_ENGINE_HASH",
    "redemptionEngine": "$REDEMPTION_ENGINE_HASH",
    "treasury": "$TREASURY_HASH",
    "branchCspr": "$BRANCH_CSPR_HASH",
    "branchSCSPR": "$BRANCH_SCSPR_HASH",
    "scsprYbToken": "$SCSPR_YBTOKEN_HASH",
    "scsprYbTokenPackage": "$SCSPR_YBTOKEN_PKG_HASH",
    "withdrawQueue": "$WITHDRAW_QUEUE_HASH"
  },
  "generatedAt": "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
}
EOF

echo "✓ Created config: $CONFIG_DIR/casper-${NETWORK}.json"

# Mirror config into frontend/public for Vercel (no env vars required)
cp "$CONFIG_DIR/casper-${NETWORK}.json" "$PUBLIC_CONFIG_DIR/casper-${NETWORK}.json"
echo "✓ Updated public config: $PUBLIC_CONFIG_DIR/casper-${NETWORK}.json"

# Update frontend .env.local
ENV_FILE="$FRONTEND_DIR/.env.local"
ENV_EXAMPLE="$FRONTEND_DIR/.env.local.example"

# Create example env file
cat > "$ENV_EXAMPLE" << EOF
# CSPR-CDP Frontend Configuration
# Auto-generated by bind-frontend.sh

# Network Configuration
NEXT_PUBLIC_CASPER_NETWORK=$NETWORK
NEXT_PUBLIC_CASPER_NODE_ADDRESS=$FRONTEND_NODE_ADDRESS
NEXT_PUBLIC_CASPER_CHAIN_NAME=$CHAIN_NAME

# Contract Addresses
NEXT_PUBLIC_REGISTRY_HASH=$REGISTRY_HASH
NEXT_PUBLIC_ROUTER_HASH=$ROUTER_HASH
NEXT_PUBLIC_ROUTER_PACKAGE_HASH=$ROUTER_PKG_HASH
NEXT_PUBLIC_STABLECOIN_HASH=$STABLECOIN_HASH
NEXT_PUBLIC_ORACLE_ADAPTER_HASH=$ORACLE_HASH
NEXT_PUBLIC_STABILITY_POOL_HASH=$STABILITY_POOL_HASH
NEXT_PUBLIC_STABILITY_POOL_PACKAGE_HASH=$STABILITY_POOL_PKG_HASH
NEXT_PUBLIC_LIQUIDATION_ENGINE_HASH=$LIQUIDATION_ENGINE_HASH
NEXT_PUBLIC_REDEMPTION_ENGINE_HASH=$REDEMPTION_ENGINE_HASH
NEXT_PUBLIC_TREASURY_HASH=$TREASURY_HASH
NEXT_PUBLIC_BRANCH_CSPR_HASH=$BRANCH_CSPR_HASH
NEXT_PUBLIC_BRANCH_SCSPR_HASH=$BRANCH_SCSPR_HASH
NEXT_PUBLIC_SCSPR_YBTOKEN_HASH=$SCSPR_YBTOKEN_HASH
NEXT_PUBLIC_SCSPR_YBTOKEN_PACKAGE_HASH=$SCSPR_YBTOKEN_PKG_HASH
NEXT_PUBLIC_WITHDRAW_QUEUE_HASH=$WITHDRAW_QUEUE_HASH

# Wallet Configuration
# Uncomment and set your preferred wallet
# NEXT_PUBLIC_DEFAULT_WALLET=casper-wallet

# API Configuration (optional)
# NEXT_PUBLIC_API_BASE_URL=https://api.cspr-cdp.io

EOF

echo "✓ Created env example: $ENV_EXAMPLE"

# Check if we should update .env.local
if [ -f "$ENV_FILE" ]; then
    echo ""
    echo "⚠ .env.local already exists at $ENV_FILE"
    echo "  Review $ENV_EXAMPLE and update manually if needed."
else
    cp "$ENV_EXAMPLE" "$ENV_FILE"
    echo "✓ Created .env.local: $ENV_FILE"
fi

echo ""
echo "=== Frontend Binding Complete ==="
echo ""
echo "Files updated:"
echo "  - $CONFIG_DIR/casper-${NETWORK}.json"
echo "  - $PUBLIC_CONFIG_DIR/casper-${NETWORK}.json"
echo "  - $ENV_EXAMPLE"
echo ""
echo "Next steps:"
echo "  1. Review frontend .env.local"
echo "  2. Start frontend: cd frontend && npm run dev"
echo "  3. Connect wallet and test"
